### ISSUE TITLE
Code Revision March 29, 2021

### ISSUE THREAD

**Issue by edwardhuh** [thepolicylab/HRcohort#1]
- [ ] `df['year'] = \
    df['year'].fillna(-1)` Is not actually doing anything. 
    If you do `df.year.value_counts()` you will realize that `-1` is not assigned to any `NaN` year. Did you see `NaN` values in the dataframe?

- [ ]  What are you trying to do in the lines:
```
df[['postal','agency','annual_salary','yrs_in_service']].replace('^_$', np.nan, inplace=True, regex=True)
df['year'].replace(-1, np.nan, inplace=True)
```
It doesnt run(largely because you cannot use `inplace = True` for a subset of the data). 
You can just do 
```
df.replace('^_$', np.nan, inplace=True, regex=True)
df['year'].replace(-1, np.nan, inplace=True)
```
(but also, re previous point about `NaN` in year.

- [ ] Have you tried running this code from start to finish? So, `str.replace` converts datatypes into `string`. It is also bad practice to convert `NaN`s into `string` when looking for patterns. A suggestion would be to set those rows with `_` separately from the other data tables, and just do string searching on those that do have values.

**Comment by khwilson** [comment]
Some small notes:
* Recommend double checking your encodings that are causing Chinese characters
* In general, if there are known NA values, then you should try to convert them into NAs at the `read_` time, e.g., `pd.read_csv(..., na_values=['_'])`
* Should run black on the code :-)
* Recommend using the relatively new `pd.NA` instead of `np.nan` and also the new `string` (not `str`) type. This will cause `.str.replace` to behave how you expect, i.e., it will skip null values.

**Comment by edwardhuh** [comment]
@waniel-dang I am closing this issue because it seems like you have done these things.
